// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// reduce_coclust
void reduce_coclust(const List& boot_nodes_l, const List& cc_ij_mat_l, NumericMatrix& cc_mat);
RcppExport SEXP _tglkmeans_reduce_coclust(SEXP boot_nodes_lSEXP, SEXP cc_ij_mat_lSEXP, SEXP cc_matSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type boot_nodes_l(boot_nodes_lSEXP);
    Rcpp::traits::input_parameter< const List& >::type cc_ij_mat_l(cc_ij_mat_lSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type cc_mat(cc_matSEXP);
    reduce_coclust(boot_nodes_l, cc_ij_mat_l, cc_mat);
    return R_NilValue;
END_RCPP
}
// reduce_num_trials
void reduce_num_trials(const List& boot_nodes_l, NumericMatrix& cc_mat);
RcppExport SEXP _tglkmeans_reduce_num_trials(SEXP boot_nodes_lSEXP, SEXP cc_matSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type boot_nodes_l(boot_nodes_lSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type cc_mat(cc_matSEXP);
    reduce_num_trials(boot_nodes_l, cc_mat);
    return R_NilValue;
END_RCPP
}
// TGL_kmeans_cpp
List TGL_kmeans_cpp(const StringVector& ids, DataFrame& mat, const int& k, const String& metric, const double& max_iter, const double& min_delta, const bool& use_cpp_random, const int& seed);
RcppExport SEXP _tglkmeans_TGL_kmeans_cpp(SEXP idsSEXP, SEXP matSEXP, SEXP kSEXP, SEXP metricSEXP, SEXP max_iterSEXP, SEXP min_deltaSEXP, SEXP use_cpp_randomSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< DataFrame& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const int& >::type k(kSEXP);
    Rcpp::traits::input_parameter< const String& >::type metric(metricSEXP);
    Rcpp::traits::input_parameter< const double& >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double& >::type min_delta(min_deltaSEXP);
    Rcpp::traits::input_parameter< const bool& >::type use_cpp_random(use_cpp_randomSEXP);
    Rcpp::traits::input_parameter< const int& >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(TGL_kmeans_cpp(ids, mat, k, metric, max_iter, min_delta, use_cpp_random, seed));
    return rcpp_result_gen;
END_RCPP
}
// downsample_matrix_cpp
Rcpp::IntegerMatrix downsample_matrix_cpp(Rcpp::IntegerMatrix input, int samples, unsigned int random_seed);
RcppExport SEXP _tglkmeans_downsample_matrix_cpp(SEXP inputSEXP, SEXP samplesSEXP, SEXP random_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type input(inputSEXP);
    Rcpp::traits::input_parameter< int >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type random_seed(random_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(downsample_matrix_cpp(input, samples, random_seed));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_downsample_sparse
Rcpp::S4 rcpp_downsample_sparse(Rcpp::S4 matrix, int samples, unsigned int random_seed);
RcppExport SEXP _tglkmeans_rcpp_downsample_sparse(SEXP matrixSEXP, SEXP samplesSEXP, SEXP random_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< int >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type random_seed(random_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_downsample_sparse(matrix, samples, random_seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tglkmeans_reduce_coclust", (DL_FUNC) &_tglkmeans_reduce_coclust, 3},
    {"_tglkmeans_reduce_num_trials", (DL_FUNC) &_tglkmeans_reduce_num_trials, 2},
    {"_tglkmeans_TGL_kmeans_cpp", (DL_FUNC) &_tglkmeans_TGL_kmeans_cpp, 8},
    {"_tglkmeans_downsample_matrix_cpp", (DL_FUNC) &_tglkmeans_downsample_matrix_cpp, 3},
    {"_tglkmeans_rcpp_downsample_sparse", (DL_FUNC) &_tglkmeans_rcpp_downsample_sparse, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_tglkmeans(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
