# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

TGL_kmeans_cpp <- function(ids, mat, k, metric, max_iter = 40, min_delta = 0.0001, random_seed = TRUE, seed = -1L) {
    .Call('_tglkmeans_TGL_kmeans_cpp', PACKAGE = 'tglkmeans', ids, mat, k, metric, max_iter, min_delta, random_seed, seed)
}

